[project]
name = "seed"
description = "SEED (Support Emerging Entrepreneurial Dreams) decentralized crowdfunding platform"
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []

[contracts.seed]
path = "contracts/seed.clar"
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
